<?php
/**
 * StreakUp Database Configuration
 * This file is automatically generated by the installer
 * Do not edit manually unless you know what you're doing
 */

// Database credentials
define('DB_HOST', 'localhost');
define('DB_NAME', 'streakup_db');
define('DB_USER', 'root');
define('DB_PASS', '');

// Create database connection
$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);

// Check connection
if ($conn->connect_error) {
    die('Database connection failed: ' . $conn->connect_error);
}

// Set charset to utf8mb4 for full Unicode support
$conn->set_charset('utf8mb4');
